# Generated by Django 3.1.7 on 2022-05-11 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'svg', 'png', 'gif', 'webp'])]),
        ),
    ]
