# Generated by Django 3.1.7 on 2022-04-05 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('f689e79c-dbc4-4802-8c2e-412d2def079e')),
        ),
    ]
