# Generated by Django 3.1.7 on 2022-04-07 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220405_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('c3b4c0bb-863c-4f17-98ce-626bd80f5391')),
        ),
    ]
