# Generated by Django 3.1.7 on 2022-04-07 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220407_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('014a66ee-7827-4a56-a7d1-06263e9023c6')),
        ),
    ]
