# Generated by Django 3.1.7 on 2022-04-11 09:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220407_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('722f7775-4d7c-4106-b1ce-adb3b8947989')),
        ),
    ]
