# Generated by Django 3.1.7 on 2022-04-11 09:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220411_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('3eb1dfa0-93c7-4635-8796-055d32b4e362')),
        ),
    ]
