# Generated by Django 3.1.7 on 2022-04-11 09:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220411_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('60190c13-c822-4488-ae5d-b4e4ec5e8d77')),
        ),
    ]
