# Generated by Django 3.1.7 on 2022-04-12 12:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220412_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('f5d47bbd-4342-4f3a-b11b-c3cdd62bc6e8')),
        ),
    ]
