# Generated by Django 3.1.7 on 2022-04-12 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220412_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('1841a99c-400e-4a99-b62d-37e98075ed6b')),
        ),
    ]
