# Generated by Django 3.1.7 on 2022-04-20 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220412_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('3a642229-c06e-4d7c-99a1-3cfc055fa731')),
        ),
    ]
