# Generated by Django 3.1.7 on 2022-04-28 10:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220420_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('185ef282-6ee6-41d7-b69f-a700ed7dd638')),
        ),
    ]
