# Generated by Django 3.1.7 on 2022-04-28 10:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20220428_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('626fa80e-bbd5-418d-a586-0736d3f006ac')),
        ),
    ]
