# Generated by Django 3.1.7 on 2022-04-28 10:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20220428_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('5e566fd4-d21f-4d81-b7cd-23847294e3a7')),
        ),
    ]
