# Generated by Django 3.1.7 on 2022-05-08 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20220506_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('d0a8cfab-ef65-445c-9651-71d6032234dd')),
        ),
    ]
