# Generated by Django 3.1.7 on 2022-05-08 12:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20220508_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('fae174d6-0bb0-4766-bc1d-789f8feab0f2')),
        ),
    ]
