# Generated by Django 3.1.7 on 2022-05-08 12:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20220508_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('807b7fd7-3db7-4478-9bc9-053138b11c9a')),
        ),
    ]
