# Generated by Django 3.1.7 on 2022-05-09 10:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20220508_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('2ea7a807-120b-48ad-b74f-ac040cc714a4')),
        ),
    ]
