# Generated by Django 3.1.7 on 2022-05-09 11:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20220509_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('1e926ee2-f1c6-49eb-ba1e-72988b90c4fb')),
        ),
    ]
