# Generated by Django 3.1.7 on 2022-05-11 21:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20220511_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('cbf2d020-0569-4e4d-8ae9-786024a27106')),
        ),
    ]
