# Generated by Django 3.1.7 on 2022-05-11 22:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20220511_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('267480ff-a5c0-4351-a3ca-175931565552')),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='phone_auth_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
