# Generated by Django 3.1.7 on 2022-05-12 11:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20220511_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('9b71d449-4fba-489d-bd44-c6aab7206ed4')),
        ),
    ]
