# Generated by Django 3.1.7 on 2022-05-12 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20220512_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('da2cff69-f3d0-488e-8761-2bdb17cef717')),
        ),
    ]
