# Generated by Django 3.1.7 on 2022-04-01 13:27

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='quill_content',
            field=django_quill.fields.QuillField(null=True),
        ),
    ]
