# Generated by Django 3.1.7 on 2022-03-30 16:31

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20220330_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaccount',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='RUB', max_digits=14),
        ),
    ]
