# Generated by Django 3.1.7 on 2022-04-07 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('providers', '0007_provider_index_traffic'),
        ('billing', '0003_auto_20220330_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaccount',
            name='provider',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.provider'),
        ),
        migrations.AlterField(
            model_name='billingaccount',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='billingaccount',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('provider__isnull', False), ('user__isnull', True)), models.Q(('provider__isnull', True), ('user__isnull', False)), _connector='OR'), name='billing_billingaccount_thing1_or_thing2'),
        ),
    ]
