# Generated by Django 3.1.7 on 2022-04-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_balancechangingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancechangingrequest',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
