# Generated by Django 3.1.7 on 2022-04-12 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_provider_index_traffic'),
        ('billing', '0006_balancechangingrequest_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaccount',
            name='bank_BIC',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='checking_account',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='correspondent_account_number',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='payee_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='tax_number',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='billingaccount',
            name='provider',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_account', to='providers.provider'),
        ),
    ]
