# Generated by Django 3.1.7 on 2022-04-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_auto_20220428_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[(0, ''), (1, 'Заморожено'), (2, 'Разморожено'), (3, 'Оплата'), (4, 'Вывод средств'), (5, 'Начисление средств'), (6, 'Комиссия')], default=(0, ''), max_length=255),
        ),
    ]
