# Generated by Django 3.1.7 on 2022-05-06 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_auto_20220502_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancechangingrequest',
            name='billing_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.billingaccount', verbose_name='Счет'),
        ),
        migrations.AlterField(
            model_name='balancechangingrequest',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Прикрепленный документ'),
        ),
        migrations.AlterField(
            model_name='balancechangingrequest',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Заявка обработана'),
        ),
    ]
