# Generated by Django 3.1.7 on 2022-05-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_auto_20220506_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancechangingrequest',
            name='bank_BIC',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='БИК Банка'),
        ),
        migrations.AddField(
            model_name='balancechangingrequest',
            name='bank_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название банка'),
        ),
        migrations.AddField(
            model_name='balancechangingrequest',
            name='checking_account',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Расчетный счет'),
        ),
        migrations.AddField(
            model_name='balancechangingrequest',
            name='correspondent_account_number',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Корреспондентский адрес счета'),
        ),
        migrations.AddField(
            model_name='balancechangingrequest',
            name='payee_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Имя плательщика'),
        ),
        migrations.AddField(
            model_name='balancechangingrequest',
            name='tax_number',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='ИНН'),
        ),
    ]
