# Generated by Django 3.1.7 on 2022-05-12 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_balancechangingrequest_blocking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancechangingrequest',
            name='blocking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.transactionblock'),
        ),
    ]
