# Generated by Django 3.1.7 on 2022-04-04 11:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_auto_20220404_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.TextField(default=uuid.UUID('147d9b74-5ffb-4d93-91a2-5ecd2cdc15a2'), unique=True),
        ),
    ]
