# Generated by Django 3.1.7 on 2022-04-04 11:04

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0005_auto_20220404_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.TextField(default=uuid.UUID('ccfe7afc-e89d-4269-af0d-9bcc9c17a5c7'), unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='chatmember',
            unique_together={('chat', 'user')},
        ),
    ]
