# Generated by Django 3.1.7 on 2022-04-05 12:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_auto_20220405_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.TextField(default=uuid.UUID('acf8cc30-c621-46df-bd02-cc0c78d4380c'), unique=True),
        ),
    ]
