# Generated by Django 3.1.7 on 2022-04-07 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_auto_20220405_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.TextField(default=uuid.UUID('557ee285-af5c-4bea-96c4-774170b13e0a'), unique=True),
        ),
    ]
