# Generated by Django 3.1.7 on 2022-04-07 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_auto_20220407_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.TextField(default=uuid.UUID('3c380500-9a67-433f-b7ff-a5247092fa08'), unique=True),
        ),
    ]
