# Generated by Django 3.1.7 on 2022-04-11 09:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_order_publication_url'),
        ('chats', '0011_auto_20220407_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.TextField(default=uuid.UUID('e4b18edf-6b8a-4b27-9f7c-6835a3d6b9e1'), unique=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.order'),
        ),
    ]
