# Generated by Django 3.1.7 on 2022-04-11 09:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_auto_20220411_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.TextField(default=uuid.UUID('f6bfb28e-bc15-4980-a8fd-7dd094f07ce7'), unique=True),
        ),
    ]
