# Generated by Django 3.1.7 on 2022-04-20 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0017_auto_20220412_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.TextField(default=uuid.UUID('1b8625df-b20f-4507-b060-a23b66111f54'), unique=True),
        ),
    ]
