# Generated by Django 3.1.7 on 2022-04-28 10:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0018_auto_20220420_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.TextField(default=uuid.UUID('631107a4-931f-4ac9-8ebc-e061472a2c7c'), unique=True),
        ),
    ]
