# Generated by Django 3.1.7 on 2022-04-28 10:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0019_auto_20220428_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.TextField(default=uuid.UUID('63ed90f7-a4eb-44bc-842a-aada3aa148b1'), unique=True),
        ),
    ]
