# Generated by Django 3.1.7 on 2022-04-28 10:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0021_auto_20220428_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.TextField(default=uuid.UUID('573af892-2afc-4001-8c10-51a4a7918a03'), unique=True),
        ),
    ]
