# Generated by Django 3.1.7 on 2022-05-02 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_order_blocking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0022_auto_20220428_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(through='chats.ChatMember', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.TextField(default=uuid.UUID('c7aca712-518f-47b7-96f0-f531feb3658b'), unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.order', verbose_name='Заказ'),
        ),
    ]
