# Generated by Django 3.1.7 on 2022-05-06 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0023_auto_20220502_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.TextField(default=uuid.UUID('5d2a4cdf-a3de-40a3-afdc-432cef8d495f'), unique=True, verbose_name='Название'),
        ),
    ]
