# Generated by Django 3.1.7 on 2022-05-08 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0024_auto_20220506_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.TextField(default=uuid.UUID('57c5f5d1-7bc7-4817-a2b4-4a3c326edfd4'), unique=True, verbose_name='Название'),
        ),
    ]
