# Generated by Django 3.1.7 on 2022-05-08 12:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0025_auto_20220508_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.TextField(default=uuid.UUID('451fa1d5-7557-45cb-b2d3-06c757ba182b'), unique=True, verbose_name='Название'),
        ),
    ]
