# Generated by Django 3.1.7 on 2022-05-09 11:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0028_auto_20220509_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.TextField(default=uuid.UUID('65666e38-35d9-44b5-914c-c31a9778ce64'), unique=True, verbose_name='Название'),
        ),
    ]
