# Generated by Django 3.1.7 on 2022-05-11 08:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0030_auto_20220509_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.TextField(default=uuid.UUID('a52dd332-9049-4d82-a6d3-d9b10ab8b90c'), unique=True, verbose_name='Название'),
        ),
    ]
