# Generated by Django 3.1.7 on 2022-05-11 20:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0031_auto_20220511_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.TextField(default=uuid.UUID('28500059-9293-461a-9832-eacd753af198'), unique=True, verbose_name='Название'),
        ),
    ]
