# Generated by Django 3.1.7 on 2022-05-11 21:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0032_auto_20220511_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.TextField(default=uuid.UUID('38eb42b5-7971-4918-a982-c66de73b6c82'), unique=True, verbose_name='Название'),
        ),
    ]
