# Generated by Django 3.1.7 on 2022-05-11 22:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0033_auto_20220511_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.TextField(default=uuid.UUID('0be1c683-7a77-4c52-a66f-eaca71e17f4e'), unique=True, verbose_name='Название'),
        ),
    ]
