# Generated by Django 3.1.7 on 2022-05-12 11:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0034_auto_20220511_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.TextField(default=uuid.UUID('fe579087-f51b-4a8a-8bce-75f76b0b70f0'), unique=True, verbose_name='Название'),
        ),
    ]
