# Generated by Django 3.1.7 on 2022-05-12 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0035_auto_20220512_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.TextField(default=uuid.UUID('a6a3d984-bf9d-4d45-8a48-6a2e26113473'), unique=True, verbose_name='Название'),
        ),
    ]
