# Generated by Django 3.1.7 on 2022-03-29 14:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderKeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderPublicationFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('url', models.URLField(null=True)),
                ('birthday', models.DateField()),
                ('index_yandex', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('index_google', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('index_yandex_news', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('index_google_news', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('index_trust_checktrust', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('index_domain_donors', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('index_spam_checktrust', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('index_IKS', models.IntegerField(default=0)),
                ('index_organic_traffic', models.IntegerField(default=0)),
                ('index_CF', models.IntegerField(default=0)),
                ('index_TF', models.IntegerField(default=0)),
                ('index_TR', models.IntegerField(default=0)),
                ('index_DR', models.IntegerField(default=0)),
                ('index_alexa_rank', models.IntegerField(default=0)),
                ('index_da_moz', models.IntegerField(default=0)),
                ('index_a_hrefs', models.IntegerField(default=0)),
                ('index_backlinks', models.IntegerField(default=0)),
                ('finded_link_exchange', models.BooleanField(default=False)),
                ('writing', models.BooleanField(default=False)),
                ('advertising_mark', models.BooleanField(default=False)),
                ('days_to_prod', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('links', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aggregators', models.ManyToManyField(blank=True, to='providers.Aggregator')),
                ('allowed_publication_themes', models.ManyToManyField(blank=True, to='providers.PublicationTheme')),
                ('city', models.ManyToManyField(to='geo.City')),
                ('country', models.ManyToManyField(to='geo.Country')),
                ('domains', models.ManyToManyField(blank=True, to='providers.ProviderDomain')),
                ('keywords', models.ManyToManyField(blank=True, to='providers.ProviderKeyWord')),
                ('languages', models.ManyToManyField(to='geo.Language')),
                ('logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.image')),
                ('state', models.ManyToManyField(to='geo.State')),
                ('themes', models.ManyToManyField(blank=True, to='providers.ProviderTheme')),
                ('types', models.ManyToManyField(blank=True, to='providers.ProviderType')),
            ],
        ),
    ]
