# Generated by Django 3.1.7 on 2022-03-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_auto_20220329_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
