# Generated by Django 3.1.7 on 2022-03-30 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_provider_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'СМИ', 'verbose_name_plural': 'СМИ'},
        ),
    ]
