# Generated by Django 3.1.7 on 2022-04-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_provider_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='index_traffic',
            field=models.IntegerField(default=0),
        ),
    ]
