# Generated by Django 3.1.7 on 2022-05-02 16:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geo', '0002_auto_20220502_1616'),
        ('providers', '0009_auto_20220428_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='status',
            field=models.CharField(choices=[('Активно', 'Активно'), ('Ожидает модерации', 'Ожидает модерации'), ('Отклонено', 'Отклонено')], default='Ожидает модерации', max_length=1000),
        ),
        migrations.AlterField(
            model_name='aggregator',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='announsmenttype',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='advertising_mark',
            field=models.BooleanField(default=False, verbose_name='Пометка о рекламе'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='aggregators',
            field=models.ManyToManyField(blank=True, to='providers.Aggregator', verbose_name='Агрегаторы'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='allowed_publication_themes',
            field=models.ManyToManyField(blank=True, to='providers.PublicationTheme', verbose_name='Разрешенные темы'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='announsment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.announsmenttype', verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='birthday',
            field=models.DateField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='city',
            field=models.ManyToManyField(to='geo.City', verbose_name='Города'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='country',
            field=models.ManyToManyField(to='geo.Country', verbose_name='Страны'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='days_to_prod',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сколько нужно дней на публикацию'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='description',
            field=django_quill.fields.QuillField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='domains',
            field=models.ManyToManyField(blank=True, to='providers.ProviderDomain', verbose_name='Домены'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Доступно ли'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='providers.ProviderKeyWord', verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='languages',
            field=models.ManyToManyField(to='geo.Language', verbose_name='Языки'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.image', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='state',
            field=models.ManyToManyField(to='geo.State', verbose_name='Области'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='themes',
            field=models.ManyToManyField(blank=True, to='providers.ProviderTheme', verbose_name='Тематики'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='url',
            field=models.URLField(null=True, verbose_name='Ссылка на сайт'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='writing',
            field=models.BooleanField(default=False, verbose_name='Есть ли написание'),
        ),
        migrations.AlterField(
            model_name='providerdomain',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='providerkeyword',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='providerpublicationformat',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='providertheme',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='providertype',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='publicationtheme',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
    ]
