# Generated by Django 3.1.7 on 2022-05-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20220506_1226'),
        ('providers', '0010_auto_20220502_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='city',
            field=models.ManyToManyField(blank=True, to='geo.City', verbose_name='Города'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='country',
            field=models.ManyToManyField(blank=True, to='geo.Country', verbose_name='Страны'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='languages',
            field=models.ManyToManyField(blank=True, to='geo.Language', verbose_name='Языки'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='state',
            field=models.ManyToManyField(blank=True, to='geo.State', verbose_name='Области'),
        ),
    ]
