# Generated by Django 3.1.7 on 2022-03-30 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220330_1125'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderadditionalitem',
            unique_together={('order', 'option')},
        ),
    ]
