# Generated by Django 3.1.7 on 2022-03-30 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0001_initial'),
        ('providers', '0005_auto_20220330_1547'),
        ('products', '0005_auto_20220330_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='executor_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executor_payment', to='billing.transaction'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.transaction'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('provider', 'type')},
        ),
    ]
