# Generated by Django 3.1.7 on 2022-03-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220331_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Оплачено', 'Paid'), ('Ожидает оплаты', 'Awaiting Payment'), ('Отменен', 'Canceled'), ('Отклонен', 'Rejected'), ('Принят в работу', 'In Progress'), ('Опубликован', 'Published'), ('Завершен', 'Done'), ('Ожидает согласования', 'Review Waiting')], default='Ожидает оплаты', max_length=100),
        ),
    ]
