# Generated by Django 3.1.7 on 2022-04-05 12:44

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20220331_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quill_solution',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quill_task',
            field=django_quill.fields.QuillField(null=True),
        ),
    ]
