# Generated by Django 3.1.7 on 2022-04-20 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0010_order_publication_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('quill_task', django_quill.fields.QuillField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Оплачено', 'Paid'), ('Ожидает оплаты', 'Awaiting Payment'), ('Отменен', 'Canceled'), ('Отклонен', 'Rejected'), ('Принят в работу', 'In Progress'), ('Опубликован', 'Published'), ('Завершен', 'Done'), ('Ожидает согласования', 'Review Waiting'), ('Ожидает публикации', 'Publish Waiting')], default='Ожидает оплаты', max_length=100),
        ),
        migrations.CreateModel(
            name='CartItemAdditionalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.cartitem')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productadditionaloption')),
            ],
            options={
                'unique_together': {('cart_item', 'option')},
            },
        ),
    ]
