# Generated by Django 3.1.7 on 2022-05-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20220506_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='productadditionaloption',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активно'),
        ),
    ]
