# Generated by Django 3.1.7 on 2022-05-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20220508_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Формат публикации', 'verbose_name_plural': 'Форматы публикаций'},
        ),
    ]
